# Generated by Django 5.0.7 on 2025-09-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emdat',
            name='classification_key',
            field=models.TextField(blank=True, db_column='Classification Key', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='country',
            field=models.TextField(blank=True, db_column='Country', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='disaster_group',
            field=models.TextField(blank=True, db_column='Disaster Group', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='disaster_type',
            field=models.TextField(blank=True, db_column='Disaster Type', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='historic',
            field=models.TextField(blank=True, db_column='Historic', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='iso',
            field=models.TextField(blank=True, db_column='ISO', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='last_update',
            field=models.TextField(blank=True, db_column='Last Update', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='no_affected',
            field=models.FloatField(blank=True, db_column='No. Affected', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='no_homeless',
            field=models.FloatField(blank=True, db_column='No. Homeless', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='no_injured',
            field=models.FloatField(blank=True, db_column='No. Injured', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='start_year',
            field=models.BigIntegerField(blank=True, db_column='Start Year', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='total_affected',
            field=models.FloatField(blank=True, db_column='Total Affected', null=True),
        ),
        migrations.AddField(
            model_name='emdat',
            name='total_deaths',
            field=models.FloatField(blank=True, db_column='Total Deaths', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='database',
            field=models.TextField(blank=True, db_column='Database', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='dataset_code',
            field=models.TextField(blank=True, db_column='Dataset Code', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='domain',
            field=models.TextField(blank=True, db_column='Domain', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='indicator',
            field=models.TextField(blank=True, db_column='Indicator', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='link',
            field=models.TextField(blank=True, db_column='Link', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='slr_indicator',
            field=models.TextField(blank=True, db_column='SLR Indicator', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='spatial_level',
            field=models.TextField(blank=True, db_column='Spatial Level', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='sub_domain',
            field=models.TextField(blank=True, db_column='Sub Domain', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='sub_topic',
            field=models.TextField(blank=True, db_column='Sub topic', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='unnamed_11',
            field=models.FloatField(blank=True, db_column='Unnamed: 11', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='unnamed_12',
            field=models.FloatField(blank=True, db_column='Unnamed: 12', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='unnamed_13',
            field=models.TextField(blank=True, db_column='Unnamed: 13', null=True),
        ),
        migrations.AddField(
            model_name='kpilist',
            name='usability',
            field=models.TextField(blank=True, db_column='Usability', null=True),
        ),
        migrations.AddField(
            model_name='pca',
            name='dataset_code',
            field=models.TextField(blank=True, db_column='dataset_code', null=True),
        ),
        migrations.AddField(
            model_name='pca',
            name='geo',
            field=models.TextField(blank=True, db_column='geo', null=True),
        ),
        migrations.AddField(
            model_name='pca',
            name='time',
            field=models.BigIntegerField(blank=True, db_column='time', null=True),
        ),
        migrations.AddField(
            model_name='pca',
            name='values',
            field=models.FloatField(blank=True, db_column='values', null=True),
        ),
        migrations.AlterModelTable(
            name='emdat',
            table='emdat',
        ),
        migrations.AlterModelTable(
            name='kpilist',
            table='kpi_list',
        ),
        migrations.AlterModelTable(
            name='pca',
            table='pca',
        ),
    ]
